# These are supported funding model platforms

github: [open-free-llm-api] # Replace with your GitHub username if you have GitHub Sponsors enabled
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective username
ko_fi: # Replace with your Ko-fi username
custom: ["https://freellms.org/"] # Replace with any custom sponsorship links
