blank_issues_enabled: false
contact_links:
  - name: Have a general question?
    url: https://github.com/freellms/freellms/discussions
    about: Please ask questions in our GitHub Discussions rather than opening an issue.
